"""empty message

Revision ID: 120dce85175e
Revises: 6d7fd6808def
Create Date: 2022-09-05 10:49:08.807291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '120dce85175e'
down_revision = '6d7fd6808def'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('universities', 'phone_num',
               existing_type=sa.String(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('universities', 'phone_num',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
