"""empty message

Revision ID: 300d6e5ef2e0
Revises: d9b4e185c5ca
Create Date: 2022-11-19 21:02:50.536546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '300d6e5ef2e0'
down_revision = 'd9b4e185c5ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('universities', sa.Column('uni_images', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('universities', 'uni_images')
    # ### end Alembic commands ###
