"""empty message

Revision ID: 391024338a98
Revises: 
Create Date: 2022-09-04 23:44:42.457723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '391024338a98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('universities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uni_name', sa.String(length=250), nullable=False),
    sa.Column('vice_chancelor', sa.String(length=250), nullable=False),
    sa.Column('vc_image', sa.String(length=250), nullable=False),
    sa.Column('uni_image', sa.String(length=250), nullable=False),
    sa.Column('about_uni', sa.String(length=250), nullable=False),
    sa.Column('location', sa.String(length=250), nullable=False),
    sa.Column('uni_website', sa.String(length=250), nullable=False),
    sa.Column('nuc_accr_courses', sa.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('universities')
    op.drop_table('states')
    # ### end Alembic commands ###
