"""empty message

Revision ID: 3b7d1a641b90
Revises: 81cfda0a9eb8
Create Date: 2022-09-15 10:29:35.192222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b7d1a641b90'
down_revision = '81cfda0a9eb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ownership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('universities', sa.Column('ownership_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'universities', 'states', ['ownership_id'], ['id'])
    
    op.execute("INSERT INTO ownership (owner) VALUES ('Private'), ('State'), ('Federal');")

    op.execute("UPDATE universities SET ownership_id = '2' WHERE ownership_id IS NULL")

    op.alter_column('universities', 'ownership_id', nullable = False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'universities', type_='foreignkey')
    op.drop_column('universities', 'ownership_id')
    op.drop_table('ownership')
    # ### end Alembic commands ###
