"""empty message

Revision ID: 531f4ef0203d
Revises: aea01ac48afd
Create Date: 2022-09-05 10:15:59.479117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '531f4ef0203d'
down_revision = 'aea01ac48afd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('universities', sa.Column('uni_name_abbr', sa.String(length=250), nullable=False))
    op.add_column('universities', sa.Column('uni_ownership', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('universities', 'uni_ownership')
    op.drop_column('universities', 'uni_name_abbr')
    # ### end Alembic commands ###
