"""empty message

Revision ID: 6d7fd6808def
Revises: 531f4ef0203d
Create Date: 2022-09-05 10:27:06.911329

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6d7fd6808def'
down_revision = '531f4ef0203d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('universities', sa.Column('contact_email', sa.String(length=250), nullable=True))
    op.add_column('universities', sa.Column('phone_num', sa.Integer(), nullable=True))
    op.alter_column('universities', 'nuc_accr_courses',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('universities', 'nuc_accr_courses',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.drop_column('universities', 'phone_num')
    op.drop_column('universities', 'contact_email')
    # ### end Alembic commands ###
