"""empty message

Revision ID: 83ce44192c09
Revises: 3b7d1a641b90
Create Date: 2022-09-15 11:14:07.385629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83ce44192c09'
down_revision = '3b7d1a641b90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('universities_ownership_id_fkey', 'universities', type_='foreignkey')
    op.create_foreign_key(None, 'universities', 'ownership', ['ownership_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'universities', type_='foreignkey')
    op.create_foreign_key('universities_ownership_id_fkey', 'universities', 'states', ['ownership_id'], ['id'])
    # ### end Alembic commands ###
