"""empty message

Revision ID: 91b8882f4cf8
Revises: 300d6e5ef2e0
Create Date: 2022-11-21 10:52:48.291387

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '91b8882f4cf8'
down_revision = '300d6e5ef2e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('universities', sa.Column('date_estb', sa.String(), nullable=True))
    op.drop_column('universities', 'date_created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('universities', sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('universities', 'date_estb')
    # ### end Alembic commands ###
