"""empty message

Revision ID: aea01ac48afd
Revises: 391024338a98
Create Date: 2022-09-05 00:20:44.682410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aea01ac48afd'
down_revision = '391024338a98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('universities', sa.Column('state_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'universities', 'states', ['state_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'universities', type_='foreignkey')
    op.drop_column('universities', 'state_id')
    # ### end Alembic commands ###
