"""empty message

Revision ID: d9b4e185c5ca
Revises: 83ce44192c09
Create Date: 2022-09-16 00:23:08.490533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9b4e185c5ca'
down_revision = '83ce44192c09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('universities', 'uni_ownership')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('universities', sa.Column('uni_ownership', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
